const FALLBACK_PREFIX = "ORG";
const PREFIX_LENGTH = 3;
const SUFFIX_DIGITS = 3;

/**
 * Derives a short, uppercase, ASCII-safe prefix for an autogenerated
 * property code from an organization's name: strips everything except
 * ASCII letters and digits, uppercases, and takes the first 3 characters
 * (fewer if the name has less, "ORG" if none at all — e.g. an
 * all-emoji/all-non-ASCII name).
 *
 * Deliberately the plain "strip and truncate" rule rather than something
 * cleverer (e.g. dropping vowels) — P6.1's investigation and this
 * checkpoint's own instructions gave worked examples that can't all be
 * satisfied by one deterministic rule ("Rent" → "RNT" implies dropping
 * vowels, but "Kiraya" → "KIR" and "ABC Realty" → "ABC" are just the
 * first 3 letters/characters as-is — vowel-dropping "Kiraya" would give
 * "KRY", not "KIR"). This rule matches the latter two exactly and stays
 * simple, predictable, and easy for a user to understand when they see
 * (and can freely edit) the suggested code.
 */
export function derivePropertyCodePrefix(organizationName: string): string {
  const alphanumeric = organizationName.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();
  return alphanumeric.slice(0, PREFIX_LENGTH) || FALLBACK_PREFIX;
}

/** Formats a prefix and sequence number as e.g. "RNT-001". */
export function formatPropertyCode(prefix: string, sequence: number): string {
  return `${prefix}-${String(sequence).padStart(SUFFIX_DIGITS, "0")}`;
}

/**
 * Extracts the numeric suffix from a property code if it exactly matches
 * `${prefix}-NNN...` (case-insensitive) — used to find the highest
 * existing suggested-format code for an organization. Existing/legacy
 * codes that don't match this exact shape are ignored, never
 * misinterpreted as a suggested-format collision.
 */
export function parsePropertyCodeSuffix(code: string, prefix: string): number | null {
  const pattern = new RegExp(`^${escapeRegExp(prefix)}-(\\d+)$`, "i");
  const match = code.trim().match(pattern);
  const digits = match?.[1];
  if (!digits) return null;
  const value = Number.parseInt(digits, 10);
  return Number.isFinite(value) ? value : null;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
