import { formatPropertyCode, parsePropertyCodeSuffix } from "@/lib/utils/propertyCode";

const FALLBACK_PREFIX = "UNT";
const PREFIX_LENGTH = 3;

/**
 * Derives a short, uppercase, ASCII-safe prefix for an autogenerated unit
 * code from its property's name: the first letter of each of the
 * property name's first 3 significant words — "Kumar Building" → "KB",
 * "Green Valley Apartments" → "GVA", "Sunrise Residency" → "SR". A
 * single-word property name falls back to that word's first 3 letters
 * (e.g. "Warehouse" → "WAR"), the same single-word fallback
 * derivePropertyCodePrefix() uses. An empty/all-punctuation/all-non-ASCII
 * name falls back to "UNT".
 *
 * Deliberately a DIFFERENT rule from derivePropertyCodePrefix() (which
 * strips punctuation and takes an organization name's first 3 characters
 * as-is) — not an oversight. P6.1-B's own worked examples ("Kiraya" →
 * "KIR", "ABC Realty" → "ABC") are best satisfied by that strip-and-
 * truncate rule; this checkpoint's worked examples ("Kumar Building" →
 * "KB", "Green Valley Apartments" → "GVA", "Sunrise Residency" → "SR")
 * are, unlike those, all exactly reproduced by word-initials. Reusing
 * derivePropertyCodePrefix() here would silently make it ambiguous about
 * which rule it implements, so this is its own small, clearly-named
 * helper instead, per P6.1-C's own instruction not to overload it.
 */
export function deriveUnitCodePrefix(propertyName: string): string {
  const words = propertyName.split(/[^a-zA-Z0-9]+/).filter(Boolean);

  if (words.length === 0) return FALLBACK_PREFIX;

  if (words.length === 1) {
    return words[0]!.toUpperCase().slice(0, PREFIX_LENGTH) || FALLBACK_PREFIX;
  }

  return (
    words
      .slice(0, PREFIX_LENGTH)
      .map((word) => word[0]!.toUpperCase())
      .join("") || FALLBACK_PREFIX
  );
}

// Reused as-is, not duplicated: neither formatPropertyCode nor
// parsePropertyCodeSuffix has anything organization/property-specific
// about it — both are pure "PREFIX-NNN" formatting/parsing (see
// propertyCode.ts). Re-exported under unit-appropriate names so call
// sites read clearly.
export { formatPropertyCode as formatUnitCode, parsePropertyCodeSuffix as parseUnitCodeSuffix };
